blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url: https://github.com/Pugmatt/BedrockConnect/wiki/Troubleshooting
    about: A set of common issues that can occur, and how to fix them.
  - name: Hosting your own BedrockConnect Instance (Linux)
    url: https://github.com/Pugmatt/BedrockConnect/wiki/Setting-up-on-Linux
    about: Setup a BedrockConnect instance on your Linux Computer
  - name: Hosting your own BedrockConnect Instance (Windows)
    url: https://www.youtube.com/watch?v=AW5X7-qnvLk
    about: Setup a BedrockConnect instance on your Windows Computer